remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Kumar Gaurav | Data Analyst Portfolio]
description: [Data Detective: Turning data mysteries into clear business insights]
